<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'article' => 
  array (
    'form_blog_comment' => '',
    'article_blog_post_list' => '',
    'article_blog_post_detail' => '',
    'article_blog_post' => 'Blog - Single post',
  ),
  'page' => 
  array (
    'page_blog' => 'Blog - List',
    'page' => 'Page',
  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2011.10.09 03:29:07 */
/* Location: D:\www\ionize\application/../themes/showcase/config/views.php */
