<div class ="search_content">
    <?php if ($this->listArticle) : ?>
        <?php foreach ($this->listArticle as $article) : ?>
    <div class ="each_article">
        &rArr; <a href ="<?php echo $this->baseUrl()?>/article/view/?id=<?php echo $article['id']?>"><?php echo $article['title']?></a>
    </div>
        <?php endforeach ?>
    <?php endif ?>
    <div class ="clear"> </div>
    <?php if (isset($this->paginator)) : ?>
    <?php
            echo $this->paginationControl($this->paginator,
                                            'Sliding',
                                            'pagin/pagination_full.phtml');

    ?>
    <?php else: ?>
    <div class ="not_found">
    Không tìm thấy kết quả nào
    </div>
    <?php endif ?>
</div>