<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
| -------------------------------------------------------------------
| IONIZE LANGUAGES
| -------------------------------------------------------------------
| Contains the available languages definitions for the front-end.
| Auto-generated by Ionizes Language administration.
|
| IMPORTANT : 
| This file has no impact on ionizes admin languages.
| For Admin languages modification, see application/languages/  
|
*/

// default language abbreviation
$config['language_abbr'] = 'en';

// available languages
$config['lang_uri_abbr'] = array(
	'en' => 'english',
	'vi' => 'Tiếng Việt'
	);

// ignore these language abbreviation : not used for the moment 
$config['lang_ignore'] = array();


/* End of file language.php */
/* Auto generated by Language Administration on : 2011.10.08 23:41:24 */
/* Location: ./application/config/language.php */
