<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'search' => 'Search',
	'simpleform' => 'Simpleform',
	'rss' => 'Rss',
	'comments' => 'Comments',
	'usermanager' => 'Usermanager',
	'demo' => 'Demo'
	);

$aliases = array(

	);

$disable_controller = array(

	);



/* End of file modules.php */
/* Auto generated by Themes Administration on : 2011.10.09 03:09:15 */
/* Location: D:\www\ionize\application//config/modules.php */
