Chào <strong><?php echo $this->full_name ?></strong>, <br/><br/>

Bạn vừa đăng ký tài khoản trên <a href = "<?php echo $this->site_link ?>"><?php echo $this->site_name ?></a> thành công.
Để hoàn tất đăng ký, bạn hãy kích hoạt tài khoản bằng cách nhấn vào đường dẫn kích hoạt dưới đây: <br/>
<a href ="<?php echo $this->active_link?>">Kích hoạt</a> (<?php echo $this->active_link ?>). <br/><br/>

-----------------------------
Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi. <br/>
Ban quản trị hệ thống.