<?php //if ($this->language == 'vi') : ?>
Chào <strong><?php echo $this->full_name ?></strong>, <br/><br/>

Có phải bạn vừa quên mật khẩu đăng nhập ở <a href = "<?php echo $this->site_link ?>"><?php echo $this->site_name ?></a>?
Nếu đúng như vậy, bạn hãy nhấn vào đường dẫn dưới đây và đăng nhập bằng mật khẩu mới bên dưới: <br/>
<a href ="<?php echo $this->reset_password_link?>">Kích hoạt</a> (<?php echo $this->reset_password_link ?>). <br/>
Mật khẩu mới: <strong><?php echo $this->new_password ?></strong>
<br/>
Sau khi đăng nhập thành công, bạn hãy đổi lại mật khẩu thân thuộc của mình để tiện cho việc đăng nhập lần sau.
<br/><br/>
-----------------------------
Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi. <br/>
Ban quản trị hệ thống.